In [11]:
import pandas as pd
import numpy as np
import datetime
import matplotlib.pyplot as plt

In [15]:
covdat_Bund = pd.read_csv('../module1-porjekt/data-RKI/RKI_Corona_Bundesl√§nder.csv')

In [14]:
covdat_Bund.head()

,OBJECTID_1,LAN_ew_AGS,LAN_ew_GEN,LAN_ew_BEZ,LAN_ew_EWZ,OBJECTID,Fallzahl,Aktualisierung,AGS_TXT,GlobalID,faelle_100000_EW,Shape__Area,Shape__Length,Death
0,1,1,Schleswig-Holstein,Land,2889821,15,1827,2020-04-07T22:00:00.000Z,1,fc5ba936-c95c-432c-8a33-9eb2f30b660f,63.221909,4.573731e+10,2.881496e+06,28
1,2,2,Hamburg,Freie und Hansestadt,1830584,6,3165,2020-04-07T22:00:00.000Z,2,0f3e860c-5181-4d3f-a421-1d51f50315ea,172.895644,2.089396e+09,4.188002e+05,23
2,3,3,Niedersachsen,Land,7962775,9,6385,2020-04-07T22:00:00.000Z,3,3fd77024-c29b-4843-9be8-682ad48e60c9,80.185614,1.299836e+11,4.008988e+06,121
3,4,4,Bremen,Freie Hansestadt,681032,5,424,2020-04-07T22:00:00.000Z,4,4132268b-54de-4327-ac1e-760e915112f1,62.258455,1.119157e+09,3.357177e+05,10
4,5,5,Nordrhein-Westfalen,Land,17912134,10,20929,2020-04-07T22:00:00.000Z,5,561d658f-3ee5-46e3-bc95-3528c6558ab9,116.842583,8.782936e+10,2.648673e+06,348

In [16]:
covdat_Land = pd.read_csv('../module1-porjekt/data-RKI/RKI_Corona_Landkreise.csv')

In [18]:
covdat_Land

,OBJECTID,ADE,GF,BSG,RS,AGS,SDV_RS,GEN,BEZ,IBZ,...,cases,deaths,cases_per_100k,cases_per_population,BL,BL_ID,county,last_update,cases7_per_100k,recovered
0,1,4.0,4.0,1.0,1001,1001.0,1.001000e+10,Flensburg,Kreisfreie Stadt,40.0,...,30,1,33.518055,0.033518,Schleswig-Holstein,1,SK Flensburg,"08.04.2020, 00:00 Uhr",5.586343,NaN
1,2,4.0,4.0,1.0,1002,1002.0,1.002000e+10,Kiel,Kreisfreie Stadt,40.0,...,171,2,69.077512,0.069078,Schleswig-Holstein,1,SK Kiel,"08.04.2020, 00:00 Uhr",18.986217,NaN
2,3,4.0,4.0,1.0,1003,1003.0,1.003000e+10,L√ºbeck,Kreisfreie Stadt,40.0,...,119,1,54.788718,0.054789,Schleswig-Holstein,1,SK L√ºbeck,"08.04.2020, 00:00 Uhr",10.589416,NaN
3,4,4.0,4.0,1.0,1004,1004.0,1.004000e+10,Neum√ºnster,Kreisfreie Stadt,40.0,...,34,0,42.774290,0.042774,Schleswig-Holstein,1,SK Neum√ºnster,"08.04.2020, 00:00 Uhr",11.322606,NaN
4,5,4.0,4.0,1.0,1051,1051.0,1.051004e+10,Dithmarschen,Kreis,42.0,...,42,1,31.529164,0.031529,Schleswig-Holstein,1,LK Dithmarschen,"08.04.2020, 00:00 Uhr",11.260416,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
407,411,NaN,NaN,NaN,11005,NaN,NaN,Berlin Spandau,Kreisfreie Stadt,NaN,...,165,4,67.629326,0.067629,Berlin,11,SK Berlin Spandau,"08.04.2020, 00:00 Uhr",27.461605,NaN
408,412,NaN,NaN,NaN,11006,NaN,NaN,Berlin Steglitz-Zehlendorf,Kreisfreie Stadt,NaN,...,343,0,111.112191,0.111112,Berlin,11,SK Berlin Steglitz-Zehlendorf,"08.04.2020, 00:00 Uhr",35.957589,NaN
409,413,NaN,NaN,NaN,11001,NaN,NaN,Berlin Mitte,Kreisfreie Stadt,NaN,...,600,0,156.180044,0.156180,Berlin,11,SK Berlin Mitte,"08.04.2020, 00:00 Uhr",35.400810,NaN
410,414,NaN,NaN,NaN,11002,NaN,NaN,Berlin Friedrichshain-Kreuzberg,Kreisfreie Stadt,NaN,...,361,3,124.585004,0.124585,Berlin,11,SK Berlin Friedrichshain-Kreuzberg,"08.04.2020, 00:00 Uhr",26.918644,NaN
411,415,NaN,NaN,NaN,11007,NaN,NaN,Berlin Tempelhof-Sch√∂neberg,Kreisfreie Stadt,NaN,...,427,3,121.429628,0.121430,Berlin,11,SK Berlin Tempelhof-Sch√∂neberg,"08.04.2020, 00:00 Uhr",34.694179,NaN

In [19]:
plt.scatter(G=covdat_Land['ObservationDate'], covdat_Land['Confirmed'])

SyntaxError: positional argument follows keyword argument (<ipython-input-19-cddafa75a75f>, line 1)