In [45]:
import pandas as pd
import requests
import json
import matplotlib
%matplotlib inline
from pandas.io.json import json_normalize
from pyjstat import pyjstat

In [6]:
base = 'http://ec.europa.eu/eurostat/wdds/rest/data/v2.1/json/en/'

In [7]:
url = base + 'med_air1?precision=1&tra_infr=AIRP_MAIN&unit=NR'

In [14]:
result = requests.get(url)

# transform the information to a dict format file
test = result.json()
type(test)

dict

In [15]:
test

{'version': '2.0',
 'label': 'Air transport infrastructure: airports',
 'href': 'http://ec.europa.eu/eurostat/wdds/rest/data/v2.1/json/en/med_air1?precision=1&tra_infr=AIRP_MAIN&unit=NR',
 'source': 'Eurostat',
 'updated': '2020-01-14',
 'status': {'26': ':',
  '27': ':',
  '83': ':',
  '92': ':',
  '93': ':',
  '94': ':',
  '95': ':',
  '96': ':',
  '97': ':'},
 'extension': {'datasetId': 'med_air1',
  'lang': 'EN',
  'description': None,
  'subTitle': None,
  'status': {'label': {':': 'not available'}}},
 'class': 'dataset',
 'value': {'0': 1,
  '1': 1,
  '2': 1,
  '3': 1,
  '4': 1,
  '5': 1,
  '6': 1,
  '7': 1,
  '8': 1,
  '9': 1,
  '10': 1,
  '11': 1,
  '12': 1,
  '13': 1,
  '14': 5,
  '15': 4,
  '16': 5,
  '17': 10,
  '18': 10,
  '19': 4,
  '20': 8,
  '21': 8,
  '22': 10,
  '23': 4,
  '24': 4,
  '25': 4,
  '28': 1,
  '29': 1,
  '30': 1,
  '31': 1,
  '32': 1,
  '33': 1,
  '34': 1,
  '35': 1,
  '36': 1,
  '37': 1,
  '38': 1,
  '39': 1,
  '40': 1,
  '41': 1,
  '42': 1,
  '43': 1,
  '44': 1,
  '45': 1,
  '46': 1,
  '47': 1,
  '48': 1,
  '49': 1,
  '50': 1,
  '51': 1,
  '52': 1,
  '53': 1,
  '54': 1,
  '55': 1,
  '56': 1,
  '57': 1,
  '58': 1,
  '59': 1,
  '60': 1,
  '61': 1,
  '62': 1,
  '63': 1,
  '64': 1,
  '65': 1,
  '66': 1,
  '67': 1,
  '68': 1,
  '69': 1,
  '70': 2,
  '71': 2,
  '72': 3,
  '73': 3,
  '74': 3,
  '75': 3,
  '76': 3,
  '77': 3,
  '78': 3,
  '79': 3,
  '80': 3,
  '81': 3,
  '82': 3,
  '84': 1,
  '85': 1,
  '86': 1,
  '87': 1,
  '88': 1,
  '89': 1,
  '90': 1,
  '91': 1,
  '98': 3,
  '99': 3,
  '100': 3,
  '101': 3,
  '102': 3,
  '103': 4,
  '104': 4,
  '105': 4,
  '106': 4,
  '107': 4,
  '108': 4,
  '109': 4,
  '110': 4,
  '111': 4},
 'dimension': {'unit': {'label': 'unit',
   'category': {'index': {'NR': 0}, 'label': {'NR': 'Number'}}},
  'tra_infr': {'label': 'tra_infr',
   'category': {'index': {'AIRP_MAIN': 0},
    'label': {'AIRP_MAIN': 'Main airports'}}},
  'geo': {'label': 'geo',
   'category': {'index': {'DZ': 0,
     'EG': 1,
     'IL': 2,
     'JO': 3,
     'LB': 4,
     'MA': 5,
     'PS': 6,
     'TN': 7},
    'label': {'DZ': 'Algeria',
     'EG': 'Egypt',
     'IL': 'Israel',
     'JO': 'Jordan',
     'LB': 'Lebanon',
     'MA': 'Morocco',
     'PS': 'Palestine',
     'TN': 'Tunisia'}}},
  'time': {'label': 'time',
   'category': {'index': {'2005': 0,
     '2006': 1,
     '2007': 2,
     '2008': 3,
     '2009': 4,
     '2010': 5,
     '2011': 6,
     '2012': 7,
     '2013': 8,
     '2014': 9,
     '2015': 10,
     '2016': 11,
     '2017': 12,
     '2018': 13},
    'label': {'2005': '2005',
     '2006': '2006',
     '2007': '2007',
     '2008': '2008',
     '2009': '2009',
     '2010': '2010',
     '2011': '2011',
     '2012': '2012',
     '2013': '2013',
     '2014': '2014',
     '2015': '2015',
     '2016': '2016',
     '2017': '2017',
     '2018': '2018'}}}},
 'id': ['unit', 'tra_infr', 'geo', 'time'],
 'size': [1, 1, 8, 14]}

In [12]:
test.keys()

dict_keys(['version', 'label', 'href', 'source', 'updated', 'status', 'extension', 'class', 'value', 'dimension', 'id', 'size'])

In [36]:
test[('dimension')]['geo']
#pd.DataFrame.from_dict(test, orient='version')

{'label': 'geo',
 'category': {'index': {'DZ': 0,
   'EG': 1,
   'IL': 2,
   'JO': 3,
   'LB': 4,
   'MA': 5,
   'PS': 6,
   'TN': 7},
  'label': {'DZ': 'Algeria',
   'EG': 'Egypt',
   'IL': 'Israel',
   'JO': 'Jordan',
   'LB': 'Lebanon',
   'MA': 'Morocco',
   'PS': 'Palestine',
   'TN': 'Tunisia'}}}

In [41]:
test[('dimension')]['time']

{'label': 'time',
 'category': {'index': {'2005': 0,
   '2006': 1,
   '2007': 2,
   '2008': 3,
   '2009': 4,
   '2010': 5,
   '2011': 6,
   '2012': 7,
   '2013': 8,
   '2014': 9,
   '2015': 10,
   '2016': 11,
   '2017': 12,
   '2018': 13},
  'label': {'2005': '2005',
   '2006': '2006',
   '2007': '2007',
   '2008': '2008',
   '2009': '2009',
   '2010': '2010',
   '2011': '2011',
   '2012': '2012',
   '2013': '2013',
   '2014': '2014',
   '2015': '2015',
   '2016': '2016',
   '2017': '2017',
   '2018': '2018'}}}

In [42]:
df = pd.DataFrame(test["dimension"])

In [43]:
df

,unit,tra_infr,geo,time
label,unit,tra_infr,geo,time
category,"{'index': {'NR': 0}, 'label': {'NR': 'Number'}}","{'index': {'AIRP_MAIN': 0}, 'label': {'AIRP_MA...","{'index': {'DZ': 0, 'EG': 1, 'IL': 2, 'JO': 3,...","{'index': {'2005': 0, '2006': 1, '2007': 2, '2..."

In [59]:

EXAMPLE_URL = 'http://ec.europa.eu/eurostat/wdds/rest/data/v2.1/json/en/med_air1?precision=1&tra_infr=AIRP_MAIN&unit=NR'

# read from json-stat
dataset = pyjstat.Dataset.read(EXAMPLE_URL)

In [60]:
dataset_from_df

Dataset([('dimension',
          OrderedDict([('unit',
                        OrderedDict([('label', 'unit'),
                                     ('category',
                                      OrderedDict([('index',
                                                    OrderedDict([('Number',
                                                                  0)])),
                                                   ('label',
                                                    OrderedDict([('Number',
                                                                  'Number')]))]))])),
                       ('tra_infr',
                        OrderedDict([('label', 'tra_infr'),
                                     ('category',
                                      OrderedDict([('index',
                                                    OrderedDict([('Main airports',
                                                                  0)])),
                                                   ('label',
                                                    OrderedDict([('Main airports',
                                                                  'Main airports')]))]))])),
                       ('geo',
                        OrderedDict([('label', 'geo'),
                                     ('category',
                                      OrderedDict([('index',
                                                    OrderedDict([('Algeria',
                                                                  0),
                                                                 ('Egypt', 1),
                                                                 ('Israel', 2),
                                                                 ('Jordan', 3),
                                                                 ('Lebanon',
                                                                  4),
                                                                 ('Morocco',
                                                                  5),
                                                                 ('Palestine',
                                                                  6),
                                                                 ('Tunisia',
                                                                  7)])),
                                                   ('label',
                                                    OrderedDict([('Algeria',
                                                                  'Algeria'),
                                                                 ('Egypt',
                                                                  'Egypt'),
                                                                 ('Israel',
                                                                  'Israel'),
                                                                 ('Jordan',
                                                                  'Jordan'),
                                                                 ('Lebanon',
                                                                  'Lebanon'),
                                                                 ('Morocco',
                                                                  'Morocco'),
                                                                 ('Palestine',
                                                                  'Palestine'),
                                                                 ('Tunisia',
                                                                  'Tunisia')]))]))])),
                       ('time',
                        OrderedDict([('label', 'time'),
                                     ('category',
                                      OrderedDict([('index',
                                                    OrderedDict([('2005', 0),
                                                                 ('2006', 1),
                                                                 ('2007', 2),
                                                                 ('2008', 3),
                                                                 ('2009', 4),
                                                                 ('2010', 5),
                                                                 ('2011', 6),
                                                                 ('2012', 7),
                                                                 ('2013', 8),
                                                                 ('2014', 9),
                                                                 ('2015', 10),
                                                                 ('2016', 11),
                                                                 ('2017', 12),
                                                                 ('2018',
                                                                  13)])),
                                                   ('label',
                                                    OrderedDict([('2005',
                                                                  '2005'),
                                                                 ('2006',
                                                                  '2006'),
                                                                 ('2007',
                                                                  '2007'),
                                                                 ('2008',
                                                                  '2008'),
                                                                 ('2009',
                                                                  '2009'),
                                                                 ('2010',
                                                                  '2010'),
                                                                 ('2011',
                                                                  '2011'),
                                                                 ('2012',
                                                                  '2012'),
                                                                 ('2013',
                                                                  '2013'),
                                                                 ('2014',
                                                                  '2014'),
                                                                 ('2015',
                                                                  '2015'),
                                                                 ('2016',
                                                                  '2016'),
                                                                 ('2017',
                                                                  '2017'),
                                                                 ('2018',
                                                                  '2018')]))]))]))])),
         ('value',
          [1.0,
           1.0,
           1.0,
           1.0,
           1.0,
           1.0,
           1.0,
           1.0,
           1.0,
           1.0,
           1.0,
           1.0,
           1.0,
           1.0,
           5.0,
           4.0,
           5.0,
           10.0,
           10.0,
           4.0,
           8.0,
           8.0,
           10.0,
           4.0,
           4.0,
           4.0,
           None,
           None,
           1.0,
           1.0,
           1.0,
           1.0,
           1.0,
           1.0,
           1.0,
           1.0,
           1.0,
           1.0,
           1.0,
           1.0,
           1.0,
           1.0,
           1.0,
           1.0,
           1.0,
           1.0,
           1.0,
           1.0,
           1.0,
           1.0,
           1.0,
           1.0,
           1.0,
           1.0,
           1.0,
           1.0,
           1.0,
           1.0,
           1.0,
           1.0,
           1.0,
           1.0,
           1.0,
           1.0,
           1.0,
           1.0,
           1.0,
           1.0,
           1.0,
           1.0,
           2.0,
           2.0,
           3.0,
           3.0,
           3.0,
           3.0,
           3.0,
           3.0,
           3.0,
           3.0,
           3.0,
           3.0,
           3.0,
           None,
           1.0,
           1.0,
           1.0,
           1.0,
           1.0,
           1.0,
           1.0,
           1.0,
           None,
           None,
           None,
           None,
           None,
           None,
           3.0,
           3.0,
           3.0,
           3.0,
           3.0,
           4.0,
           4.0,
           4.0,
           4.0,
           4.0,
           4.0,
           4.0,
           4.0,
           4.0]),
         ('version', '2.0'),
         ('class', 'dataset'),
         ('updated', '2020-04-08T16:42:54.232366'),
         ('source', 'Self-elaboration'),
         ('id', ['unit', 'tra_infr', 'geo', 'time']),
         ('size', [1, 1, 8, 14])])

In [71]:

# write to dataframe
df = dataset.write('dataframe')
print(df)
#type(df)

       unit       tra_infr      geo  time  value
0    Number  Main airports  Algeria  2005    1.0
1    Number  Main airports  Algeria  2006    1.0
2    Number  Main airports  Algeria  2007    1.0
3    Number  Main airports  Algeria  2008    1.0
4    Number  Main airports  Algeria  2009    1.0
..      ...            ...      ...   ...    ...
107  Number  Main airports  Tunisia  2014    4.0
108  Number  Main airports  Tunisia  2015    4.0
109  Number  Main airports  Tunisia  2016    4.0
110  Number  Main airports  Tunisia  2017    4.0
111  Number  Main airports  Tunisia  2018    4.0

[112 rows x 5 columns]

In [75]:

EXAMPLE_URL = "http://ec.europa.eu/eurostat/wdds/rest/data/v2.1/json/en/urb_cpop1?indic_ur=DE1001V&indic_ur=DE1002V&indic_ur=DE1003V&indic_ur=DE1025V&indic_ur=DE1026V&indic_ur=DE1027V&indic_ur=DE1028V&indic_ur=DE1029V&indic_ur=DE1030V&indic_ur=DE1040V&indic_ur=DE1041V&indic_ur=DE1042V&indic_ur=DE1046V&indic_ur=DE1047V&indic_ur=DE1048V&indic_ur=DE1049V&indic_ur=DE1050V&indic_ur=DE1051V&indic_ur=DE1055V&indic_ur=DE1056V&indic_ur=DE1057V&indic_ur=DE1058V&indic_ur=DE1059V&indic_ur=DE1060V&indic_ur=DE1061V&indic_ur=DE1062V&indic_ur=DE1063V&indic_ur=DE1064V&indic_ur=DE1065V&indic_ur=DE1066V&indic_ur=DE1074V&indic_ur=DE1075V&indic_ur=DE1076V&indic_ur=DE1077V&indic_ur=DE1078V&indic_ur=DE1079V&sinceTimePeriod=2010&geoLevel=country&geoLevel=city&groupedIndicators=1&precision=1"


# read from json-stat
dataset = pyjstat.Dataset.read(EXAMPLE_URL)


# write to dataframe
df2 = dataset.write('dataframe')
print(df)
#type(df)

                                                 indic_ur  \
0                 Population on the 1st of January, total
1                 Population on the 1st of January, total
2                 Population on the 1st of January, total
3                 Population on the 1st of January, total
4                 Population on the 1st of January, total
...                                                   ...
387355  Population on the 1st of January, 10-14 years,...
387356  Population on the 1st of January, 10-14 years,...
387357  Population on the 1st of January, 10-14 years,...
387358  Population on the 1st of January, 10-14 years,...
387359  Population on the 1st of January, 10-14 years,...

                                            cities  time      value
0                                          Austria  2010        NaN
1                                          Austria  2011        NaN
2                                          Austria  2012        NaN
3                                          Austria  2013  8451860.0
4                                          Austria  2014  8507786.0
...                                            ...   ...        ...
387355  Derry & Strabane Local Government District  2015     4660.0
387356  Derry & Strabane Local Government District  2016     4646.0
387357  Derry & Strabane Local Government District  2017     4642.0
387358  Derry & Strabane Local Government District  2018     4714.0
387359  Derry & Strabane Local Government District  2019        NaN

[387360 rows x 4 columns]

In [79]:

EXAMPLE_URL = "https://appsso.eurostat.ec.europa.eu/nui/show.do?dataset=demo_gind&lang=en"

# read from json-stat
dataset = pyjstat.Dataset.read(EXAMPLE_URL)


# write to dataframe
df3 = dataset.write('dataframe')
print(df)
#type(df)

JSONDecodeError: Expecting value: line 1 column 1 (char 0)

In [76]:
print(df2)

                                                 indic_ur  \
0                 Population on the 1st of January, total
1                 Population on the 1st of January, total
2                 Population on the 1st of January, total
3                 Population on the 1st of January, total
4                 Population on the 1st of January, total
...                                                   ...
387355  Population on the 1st of January, 10-14 years,...
387356  Population on the 1st of January, 10-14 years,...
387357  Population on the 1st of January, 10-14 years,...
387358  Population on the 1st of January, 10-14 years,...
387359  Population on the 1st of January, 10-14 years,...

                                            cities  time      value
0                                          Austria  2010        NaN
1                                          Austria  2011        NaN
2                                          Austria  2012        NaN
3                                          Austria  2013  8451860.0
4                                          Austria  2014  8507786.0
...                                            ...   ...        ...
387355  Derry & Strabane Local Government District  2015     4660.0
387356  Derry & Strabane Local Government District  2016     4646.0
387357  Derry & Strabane Local Government District  2017     4642.0
387358  Derry & Strabane Local Government District  2018     4714.0
387359  Derry & Strabane Local Government District  2019        NaN

[387360 rows x 4 columns]